### ISSUE TITLE
Build fails with LTO

### ISSUE THREAD

**Issue by eli-schwartz** [arcress0/ipmiutil#21]
```
x86_64-pc-linux-gnu-gcc  -march=native -fstack-protector-all -O2 -pipe -fdiagnostics-color=always -frecord-gcc-switches -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-clash-protection -flto=4 -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing  -Wformat -Werror=format-security -Werror=implicit-function-declaration -Werror=implicit-int -Werror=int-conversion -Werror=incompatible-pointer-types -o iseltime iseltime.o libipmiutil.a -Wl,-O1 -Wl,--as-needed -flto=4 -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing -Wl,--defsym=__gentoo_check_ldflags__=0  -lpthread  ../lib/libipmi_lanplus.a -lcrypto 
x86_64-pc-linux-gnu-gcc -march=native -fstack-protector-all -O2 -pipe -fdiagnostics-color=always -frecord-gcc-switches -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-clash-protection -flto=4 -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing  -Wformat -Werror=format-security -Werror=implicit-function-declaration -Werror=implicit-int -Werror=int-conversion -Werror=incompatible-pointer-types -o ipmi_sample ipmi_sample.o libipmiutil.a -Wl,-O1 -Wl,--as-needed -flto=4 -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing -Wl,--defsym=__gentoo_check_ldflags__=0  ../lib/libipmi_lanplus.a -lcrypto
ipmicmd.c:197:12: error: type of ‘ipmi_cmdraw_ia’ does not match original declaration [-Werror=lto-type-mismatch]
  197 | extern int ipmi_cmdraw_ia( uchar cmd, uchar netfn, uchar lun, uchar sa,
      |            ^
imbapi.c:863:5: note: type mismatch in parameter 7
  863 | int ipmi_cmdraw_ia(BYTE cmd, BYTE netfn, BYTE lun, BYTE sa, BYTE bus,
      |     ^
imbapi.c:863:5: note: type ‘BYTE’ should match type ‘int’
imbapi.c:863:5: note: ‘ipmi_cmdraw_ia’ was previously declared here
ipmicmd.c:216:12: error: type of ‘ipmi_open_direct’ does not match original declaration [-Werror=lto-type-mismatch]
  216 | extern int ipmi_open_direct(char fdebug);
      |            ^
ipmidir.c:392:5: note: type mismatch in parameter 1
  392 | int ipmi_open_direct(int fdebugcmd)
      |     ^
ipmidir.c:392:5: note: type ‘int’ should match type ‘char’
ipmidir.c:392:5: note: ‘ipmi_open_direct’ was previously declared here
ipmicmd.c:197:12: error: type of ‘ipmi_cmdraw_ia’ does not match original declaration [-Werror=lto-type-mismatch]
  197 | extern int ipmi_cmdraw_ia( uchar cmd, uchar netfn, uchar lun, uchar sa,
      |            ^
imbapi.c:863:5: note: type mismatch in parameter 7
  863 | int ipmi_cmdraw_ia(BYTE cmd, BYTE netfn, BYTE lun, BYTE sa, BYTE bus,
      |     ^
imbapi.c:863:5: note: type ‘BYTE’ should match type ‘int’
imbapi.c:863:5: note: ‘ipmi_cmdraw_ia’ was previously declared here
ipmicmd.c:216:12: error: type of ‘ipmi_open_direct’ does not match original declaration [-Werror=lto-type-mismatch]
  216 | extern int ipmi_open_direct(char fdebug);
      |            ^
ipmidir.c:392:5: note: type mismatch in parameter 1
  392 | int ipmi_open_direct(int fdebugcmd)
      |     ^
ipmidir.c:392:5: note: type ‘int’ should match type ‘char’
ipmidir.c:392:5: note: ‘ipmi_open_direct’ was previously declared here
itsol.h:61:5: error: type of ‘open_sockfd’ does not match original declaration [-Werror=lto-type-mismatch]
   61 | int open_sockfd(char *node, SockType *sfd, SOCKADDR_T  *daddr,
      |     ^
ipmilan.c:531:5: note: type mismatch in parameter 2
  531 | int open_sockfd(char *node, int port, SockType *sfd, SOCKADDR_T  *daddr,
      |     ^
ipmilan.c:531:5: note: ‘open_sockfd’ was previously declared here
ipmilan.c:531:5: note: code may be misoptimized unless ‘-fno-strict-aliasing’ is used
isol.c:145:13: error: type of ‘lan_keepalive’ does not match original declaration [-Werror=lto-type-mismatch]
  145 | extern int  lan_keepalive(int type);
      |             ^
ipmilan.c:2218:6: note: type mismatch in parameter 1
 2218 | int  lan_keepalive( uchar bType )
      |      ^
ipmilan.c:2218:6: note: type ‘unsigned char’ should match type ‘int’
ipmilan.c:2218:6: note: ‘lan_keepalive’ was previously declared here
ievents.c:629:12: error: type of ‘GetSensorType’ does not match original declaration [-Werror=lto-type-mismatch]
  629 | extern int GetSensorType(int snum, uchar *stype, uchar *rtype);
      |            ^
isensor.c:1111:5: note: type mismatch in parameter 1
 1111 | int GetSensorType(uchar snum, uchar *stype, uchar *rtype)
      |     ^
isensor.c:1111:5: note: type ‘unsigned char’ should match type ‘int’
isensor.c:1111:5: note: ‘GetSensorType’ was previously declared here
ievents.c:627:14: error: type of ‘get_unit_type’ does not match original declaration [-Werror=lto-type-mismatch]
  627 | extern char *get_unit_type(uchar iunit, uchar ibase, uchar imod, int flg);
      |              ^
isensor.c:628:7: note: type mismatch in parameter 1
  628 | char *get_unit_type(int iunits, int ibase, int imod, int fshort)
      |       ^
isensor.c:628:7: note: type ‘int’ should match type ‘unsigned char’
isensor.c:628:7: note: ‘get_unit_type’ was previously declared here
ievents.c:784:13: error: type of ‘get_MemDesc’ does not match original declaration [-Werror=lto-type-mismatch]
  784 | extern int  get_MemDesc(int array, int dimm, char *desc, int *psz); /*mem_if.c*/
      |             ^
mem_if.c:617:5: note: type mismatch in parameter 1
  617 | int get_MemDesc(UCHAR array, UCHAR dimm, char *desc, int *psize)
      |     ^
mem_if.c:617:5: note: type ‘UCHAR’ should match type ‘int’
mem_if.c:617:5: note: ‘get_MemDesc’ was previously declared here
make: TMPDIR value /tmp/iu/ipmiutil-3.1.9: No such file or directory
make: using default temporary directory '/tmp'
make: TMPDIR value /tmp/iu/ipmiutil-3.1.9: No such file or directory
make: using default temporary directory '/tmp'
lto1: some warnings being treated as errors
lto-wrapper: fatal error: x86_64-pc-linux-gnu-gcc returned 1 exit status
compilation terminated.
/usr/lib/gcc/x86_64-pc-linux-gnu/13/../../../../x86_64-pc-linux-gnu/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1033: libipmiutil.so.1] Error 1
make[2]: *** Waiting for unfinished jobs....
ipmicmd.c:197:12: error: type of ‘ipmi_cmdraw_ia’ does not match original declaration [-Werror=lto-type-mismatch]
  197 | extern int ipmi_cmdraw_ia( uchar cmd, uchar netfn, uchar lun, uchar sa,
      |            ^
imbapi.c:863:5: note: type mismatch in parameter 7
  863 | int ipmi_cmdraw_ia(BYTE cmd, BYTE netfn, BYTE lun, BYTE sa, BYTE bus,
      |     ^
imbapi.c:863:5: note: type ‘BYTE’ should match type ‘int’
imbapi.c:863:5: note: ‘ipmi_cmdraw_ia’ was previously declared here
ipmicmd.c:216:12: error: type of ‘ipmi_open_direct’ does not match original declaration [-Werror=lto-type-mismatch]
  216 | extern int ipmi_open_direct(char fdebug);
      |            ^
ipmidir.c:392:5: note: type mismatch in parameter 1
  392 | int ipmi_open_direct(int fdebugcmd)
      |     ^
ipmidir.c:392:5: note: type ‘int’ should match type ‘char’
ipmidir.c:392:5: note: ‘ipmi_open_direct’ was previously declared here
ipmicmd.c:197:12: error: type of ‘ipmi_cmdraw_ia’ does not match original declaration [-Werror=lto-type-mismatch]
  197 | extern int ipmi_cmdraw_ia( uchar cmd, uchar netfn, uchar lun, uchar sa,
      |            ^
imbapi.c:863:5: note: type mismatch in parameter 7
  863 | int ipmi_cmdraw_ia(BYTE cmd, BYTE netfn, BYTE lun, BYTE sa, BYTE bus,
      |     ^
imbapi.c:863:5: note: type ‘BYTE’ should match type ‘int’
imbapi.c:863:5: note: ‘ipmi_cmdraw_ia’ was previously declared here
ipmicmd.c:216:12: error: type of ‘ipmi_open_direct’ does not match original declaration [-Werror=lto-type-mismatch]
  216 | extern int ipmi_open_direct(char fdebug);
      |            ^
ipmidir.c:392:5: note: type mismatch in parameter 1
  392 | int ipmi_open_direct(int fdebugcmd)
      |     ^
ipmidir.c:392:5: note: type ‘int’ should match type ‘char’
ipmidir.c:392:5: note: ‘ipmi_open_direct’ was previously declared here
lto1: some warnings being treated as errors
lto-wrapper: fatal error: x86_64-pc-linux-gnu-gcc returned 1 exit status
compilation terminated.
/usr/lib/gcc/x86_64-pc-linux-gnu/13/../../../../x86_64-pc-linux-gnu/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1106: iseltime] Error 1
lto1: some warnings being treated as errors
lto-wrapper: fatal error: x86_64-pc-linux-gnu-gcc returned 1 exit status
compilation terminated.
/usr/lib/gcc/x86_64-pc-linux-gnu/13/../../../../x86_64-pc-linux-gnu/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
```

Exhaustive build log: [build.log](https://github.com/arcress0/ipmiutil/files/14440942/build.log)
Downstream report: https://bugs.gentoo.org/863590

**Comment by arcress0** [comment]
This is odd.  Apparently the typedef of BYTE as unsigned char is not included in certain cases,  I'll address this in the upcoming ipmiutil release.

**Comment by arcress0** [comment]
I'm hoping that this is resolved in ipmiutil-3.2.0, but I cannot verify since I don't have an LTO environment to test.

**Comment by eli-schwartz** [comment]
You should be able to reproduce it anywhere by just adding a couple of GCC compile arguments.

In my case, I tried to build with the following {C,CXX,FC,LD}FLAGS (for ipmiutil I suppose that only CFLAGS and LDFLAGS are relevant though): `-flto=4 -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing`

Any GCC version should reproduce -- I usually test with GCC 14 but can confirm even GCC 10 will detect this issue when using the above mentioned CFLAGS for ipmiutil 3.1.9.

**Comment by eli-schwartz** [comment]
I just attempted to build the new 3.2.0 release. It still fails, e.g.

```
$ export CFLAGS="${CFLAGS} -flto=4 -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing"
$ export LDFLAGS="${LDFLAGS} -flto=4 -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing"

$ ebuild ipmiutil-3.2.0.ebuild clean install

[...]

make[2]: Entering directory '/var/tmp/portage/sys-apps/ipmiutil-3.2.0/work/ipmiutil-3.2.0/util'
x86_64-pc-linux-gnu-gcc  -pipe -march=native -fstack-protector-all -O2 -fdiagnostics-color=always -frecord-gcc-switches -flto=4 -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing  -Wformat -Werror=format-security -o iseltime iseltime.o libipmiutil.a -Wl,-O1 -Wl,--as-needed -Wl,-z,pack-relative-relocs -flto=4 -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing -Wl,--defsym=__gentoo_check_ldflags__=0  -lpthread  ../lib/libipmi_lanplus.a -lcrypto 
make: TMPDIR value /tmp/iu/ipmiutil-3.2.0: No such file or directory
make: using default temporary directory '/tmp'
ipmicmd.c:197:12: error: type of ‘ipmi_cmdraw_ia’ does not match original declaration [-Werror=lto-type-mismatch]
  197 | extern int ipmi_cmdraw_ia( uchar cmd, uchar netfn, uchar lun, uchar sa,
      |            ^
imbapi.c:863:5: note: type mismatch in parameter 7
  863 | int ipmi_cmdraw_ia(BYTE cmd, BYTE netfn, BYTE lun, BYTE sa, BYTE bus,
      |     ^
imbapi.c:863:5: note: type ‘BYTE’ should match type ‘int’
imbapi.c:863:5: note: ‘ipmi_cmdraw_ia’ was previously declared here
lto1: some warnings being treated as errors
lto-wrapper: fatal error: x86_64-pc-linux-gnu-gcc returned 1 exit status
compilation terminated.
/usr/lib/gcc/x86_64-pc-linux-gnu/14/../../../../x86_64-pc-linux-gnu/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1105: iseltime] Error 1
```

**Comment by arcress0** [comment]
I have applied an update that appears to resolve this in ipmiutil-3.2.1, but would like you to confirm it before pushing this out.  Here is the updated tarball -  https://ipmiutil.sourceforge.net/FILES/ipmiutil-3.2.1.tar.gz

**Comment by eli-schwartz** [comment]
Thanks. It got a lot further this time but there are still a couple issues.

```
x86_64-pc-linux-gnu-gcc -pipe -march=native -fstack-protector-all -O2 -fdiagnostics-color=always -frecord-gcc-switches -flto=4 -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing  -Wformat -Werror=format-security -Wl,-O1 -Wl,--as-needed -Wl,-z,pack-relative-relocs -flto=4 -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing -Wl,--defsym=__gentoo_check_ldflags__=0 -o ipmiutil ipmiutil.o ialarms.o ihealth.o ievents.o ifru.o ifru_picmg.o igetevent.o ireset.o icmd.o ilan.o isensor.o isel.o iserial.o iwdt.o isol.o idiscover.o iconfig.o ipicmg.o ifirewall.o ifwum.o ihpm.o itsol.o idcmi.o iuser.o oem_kontron.o oem_fujitsu.o oem_intel.o oem_sun.o oem_supermicro.o oem_dell.o oem_quanta.o oem_hp.o oem_newisys.o oem_lenovo.o oem_asus.o iekanalyzer.o ipmicmd.o mem_if.o ipmidir.o imbapi.o ipmimv.o ipmild.o ipmibmc.o ipmilipmi.o subs.o md5.o md2.o ipmilan.o ipmilanplus.o  -lpthread  ../lib/libipmi_lanplus.a -lcrypto  
itsol.h:61:5: error: type of ‘open_sockfd’ does not match original declaration [-Werror=lto-type-mismatch]
   61 | int open_sockfd(char *node, SockType *sfd, SOCKADDR_T  *daddr,
      |     ^
ipmilan.c:531:5: note: type mismatch in parameter 2
  531 | int open_sockfd(char *node, int port, SockType *sfd, SOCKADDR_T  *daddr,
      |     ^
ipmilan.c:531:5: note: ‘open_sockfd’ was previously declared here
ipmilan.c:531:5: note: code may be misoptimized unless ‘-fno-strict-aliasing’ is used
isol.c:145:13: error: type of ‘lan_keepalive’ does not match original declaration [-Werror=lto-type-mismatch]
  145 | extern int  lan_keepalive(int type);
      |             ^
ipmilan.c:2218:6: note: type mismatch in parameter 1
 2218 | int  lan_keepalive( uchar bType )
      |      ^
ipmilan.c:2218:6: note: type ‘unsigned char’ should match type ‘int’
ipmilan.c:2218:6: note: ‘lan_keepalive’ was previously declared here
ievents.c:629:12: error: type of ‘GetSensorType’ does not match original declaration [-Werror=lto-type-mismatch]
  629 | extern int GetSensorType(int snum, uchar *stype, uchar *rtype);
      |            ^
isensor.c:1111:5: note: type mismatch in parameter 1
 1111 | int GetSensorType(uchar snum, uchar *stype, uchar *rtype)
      |     ^
isensor.c:1111:5: note: type ‘unsigned char’ should match type ‘int’
isensor.c:1111:5: note: ‘GetSensorType’ was previously declared here
ievents.c:627:14: error: type of ‘get_unit_type’ does not match original declaration [-Werror=lto-type-mismatch]
  627 | extern char *get_unit_type(uchar iunit, uchar ibase, uchar imod, int flg);
      |              ^
isensor.c:628:7: note: type mismatch in parameter 1
  628 | char *get_unit_type(int iunits, int ibase, int imod, int fshort)
      |       ^
isensor.c:628:7: note: type ‘int’ should match type ‘unsigned char’
isensor.c:628:7: note: ‘get_unit_type’ was previously declared here
lto1: some warnings being treated as errors
lto-wrapper: fatal error: x86_64-pc-linux-gnu-gcc returned 1 exit status
compilation terminated.
/usr/lib/gcc/x86_64-pc-linux-gnu/14/../../../../x86_64-pc-linux-gnu/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1118: ipmiutil] Error 1
```

```
x86_64-pc-linux-gnu-gcc -pipe -march=native -fstack-protector-all -O2 -fdiagnostics-color=always -frecord-gcc-switches -flto=4 -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing  -Wformat -Werror=format-security -o ipmi_sample_evt ipmi_sample_evt.o isensor2.o ievents2.o libipmiutil.a -Wl,-O1 -Wl,--as-needed -Wl,-z,pack-relative-relocs -flto=4 -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing -Wl,--defsym=__gentoo_check_ldflags__=0  ../lib/libipmi_lanplus.a -lcrypto
ievents.c:681:12: error: type of ‘GetSensorType’ does not match original declaration [-Werror=lto-type-mismatch]
  681 | extern int GetSensorType(int snum, uchar *stype, uchar *rtype);
      |            ^
isensor.c:1111:5: note: type mismatch in parameter 1
 1111 | int GetSensorType(uchar snum, uchar *stype, uchar *rtype)
      |     ^
isensor.c:1111:5: note: type ‘unsigned char’ should match type ‘int’
isensor.c:1111:5: note: ‘GetSensorType’ was previously declared here
ievents.c:679:14: error: type of ‘get_unit_type’ does not match original declaration [-Werror=lto-type-mismatch]
  679 | extern char *get_unit_type(uchar iunit, uchar ibase, uchar imod, int flg);
      |              ^
isensor.c:628:7: note: type mismatch in parameter 1
  628 | char *get_unit_type(int iunits, int ibase, int imod, int fshort)
      |       ^
isensor.c:628:7: note: type ‘int’ should match type ‘unsigned char’
isensor.c:628:7: note: ‘get_unit_type’ was previously declared here
lto1: some warnings being treated as errors
lto-wrapper: fatal error: x86_64-pc-linux-gnu-gcc returned 1 exit status
compilation terminated.
/usr/lib/gcc/x86_64-pc-linux-gnu/14/../../../../x86_64-pc-linux-gnu/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1084: ipmi_sample_evt] Error 1
```

**Comment by arcress0** [comment]
OK, made those changes also.  Please verify that it works for you.

**Comment by eli-schwartz** [comment]
Still one last failure:

```
x86_64-pc-linux-gnu-gcc -pipe -march=native -fstack-protector-all -O2 -fdiagnostics-color=always -frecord-gcc-switches -flto=4 -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing  -Wformat -Werror=format-security -o ipmi_sample_evt ipmi_sample_evt.o isensor2.o ievents2.o libipmiutil.a -Wl,-O1 -Wl,--as-needed -Wl,-z,pack-relative-relocs -flto=4 -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing -Wl,--defsym=__gentoo_check_ldflags__=0  ../lib/libipmi_lanplus.a -lcrypto
ievents.c:681:12: error: type of ‘GetSensorType’ does not match original declaration [-Werror=lto-type-mismatch]
  681 | extern int GetSensorType(int snum, uchar *stype, uchar *rtype);
      |            ^
isensor.c:1111:5: note: type mismatch in parameter 1
 1111 | int GetSensorType(uchar snum, uchar *stype, uchar *rtype)
      |     ^
isensor.c:1111:5: note: type ‘unsigned char’ should match type ‘int’
isensor.c:1111:5: note: ‘GetSensorType’ was previously declared here
lto1: some warnings being treated as errors
lto-wrapper: fatal error: x86_64-pc-linux-gnu-gcc returned 1 exit status
compilation terminated.
/usr/lib/gcc/x86_64-pc-linux-gnu/14/../../../../x86_64-pc-linux-gnu/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1084: ipmi_sample_evt] Error 1
```

**Comment by arcress0** [comment]
OK, thanks.  Updated ipmiutil-3.2.1.tar.gz with that now also.

**Comment by eli-schwartz** [comment]
Thanks! Now it fully builds.

**Comment by arcress0** [comment]
This has now been merged into SF and github with ipmiutil-3.2.1

**Comment by thesamesam** [comment]
Confirmed - thank you!
